<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class BrandRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules=[
            'name'=>'required|unique:brands,name',
            'slug_name'=>'required|unique:brands,slug_name'
        ];
        if($this->route()->named('brands.update')){
//            dd();
            $rules['name'] .= ','. $this->route()->parameter('brand')->id;
            $rules['slug_name'] .= ','. $this->route()->parameter('brand')->id;
        }
        return $rules;
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
